name: Gatsby PR build

on:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '20'
      - name: Get latest npm version
        run: npm install -g npm@latest --prefix .
      - name: Install dependencies
        run: npm install --prefer-offline --no-audit
      - name: Validate SIP, STP, SR & SCCP frontmatters
        run: npm test
